name: wave
description: Widget for displaying waves with custom color, duration, floating and blur effects.
version: 0.1.0
homepage: https://github.com/i-protoss/wave

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
